## Cluster Settings
cluster.name: "docker-cluster"
network.host: 0.0.0.0

## License
xpack.license.self_generated.type: trial

# Security
xpack.security.enabled: true
xpack.monitoring.collection.enabled: false

# transport settings
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: none
xpack.security.transport.ssl.certificate: ${CONFIG_DIR}/elasticsearch.crt
xpack.security.transport.ssl.certificate_authorities: ${CONFIG_DIR}/ca.crt
xpack.security.transport.ssl.key: ${CONFIG_DIR}/elasticsearch.key

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: ${CONFIG_DIR}/elasticsearch.key
xpack.security.http.ssl.certificate_authorities: ${CONFIG_DIR}/ca.crt
xpack.security.http.ssl.certificate: ${CONFIG_DIR}/elasticsearch.crt