version: '3.5'

services:
    swag:
      image: linuxserver/swag
      container_name: swag
      cap_add:
        - NET_ADMIN
      environment:
        - PUID=2000
        - PGID=2000
        - TZ=${TIMEZONE}
        - URL=${DOMAIN}
        - SUBDOMAINS=${SUBDOMAIN}
        - VALIDATION=http
        - EMAIL=${EMAIL}
        - STAGING=false
      volumes:
        - ./swag/kibana.subdomain.conf:/config/nginx/proxy-confs/kibana.subdomain.conf
        - ./swag:/config
      ports:
        - 443:443
        - 80:80
      restart: unless-stopped
      networks:
        - elk

networks:
  elk:
    driver: bridge