filebeat.inputs:
    - type: tcp
      enabled: true
      max_message_size: 10MiB
      host: "filebeat:9000"
   #   - type: log
   #   paths:
   #     - /var/log/system.log
   #     - /var/log/wifi.log
  #  - type: log
  #    paths:
  #      - "/var/log/apache2/*"
  #    fields:
  #      apache: true
 #     fields_under_root: true

output.logstash:
    hosts: ["logstash:5044"]
