---
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "https://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true


# X-Pack Security

elasticsearch.username: "${ELASTIC_USERNAME}"
elasticsearch.password: "${ELASTIC_PASSWORD}"
xpack.encryptedSavedObjects.encryptionKey: "${ENCRYPTION_KEY}"

server.ssl.enabled: true
server.ssl.certificate: ${CONFIG_DIR}/kibana.crt
server.ssl.key: ${CONFIG_DIR}/kibana.key

elasticsearch.ssl.certificateAuthorities: [ "${CONFIG_DIR}/ca.crt" ]
